### ISSUE TITLE
remove mmmagic as a dependency?

### ISSUE THREAD

**Issue by dacbd** [iterative/cml#836] opened 2021-12-06 21:00 UTC
I was looking at: https://github.com/iterative/setup-cml/issues/53

How much work would it be to eliminate as a dependency? It seems to be only used in one place, I'm not familiar with this chunk: https://github.com/iterative/cml/blob/cf7bfd039bc366d781ee897f774ca394f21e3f39/src/utils.js#L27-L47

and if IIRC is the only complied cml dependency?

**Comment by dacbd** [comment] 2021-12-06 21:02
This would only be a change of convenience.

**Comment by 0x2b3bfa0** [comment] 2021-12-06 22:29
Duplicate of #544?

**Comment by 0x2b3bfa0** [comment] 2021-12-06 22:29
I wonder if we _really_ need a MIME type library on the client side.

**Comment by dacbd** [comment] 2021-12-06 22:42
I haven't seen where this utils function is being used but I'm just guessing this for publish or send-comment to make sure its a filetype that plays nice with github/gitlab comments / mardown embedding etc?

If that's the case how much protection of the user using the tool incorrectly do you really need to do?

**Comment by casperdcl** [comment] 2021-12-07 12:01
closing as duplicate of #544

**Closed by casperdcl** 2021-12-07 12:01 UTC
