### ISSUE TITLE
Invalid URL error

### ISSUE THREAD

**Issue by Sandy0002** [iterative/cml#1423] opened 2023-09-10 18:31 UTC
I am just getting started with CML hence looking for the help with this error. 

I am generating feature_importance and residuals images from my program and passing it in cml.yaml file in report generation. I used below code but it is showing Invalid URL error.

  name: your-workflow-name
  on: [push]
  jobs:
    run:
      runs-on: ubuntu-latest
      # optionally use a convenient Ubuntu LTS + DVC + CML image
      # container: ghcr.io/iterative/cml:0-dvc2-base1
      steps:
        - uses: actions/checkout@v3
        # may need to setup NodeJS & Python3 on e.g. self-hosted
        # - uses: actions/setup-node@v3
        #   with:
        #     node-version: '16'
        # - uses: actions/setup-python@v4
        #   with:
        #     python-version: '3.x'
        - uses: iterative/setup-cml@v1
        - name: Train model
          run: |
            # Your ML workflow goes here
            pip install -r requirements.txt
            python train.py
        - name: Write CML report
          env:
            REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            # Post reports as comments in GitHub PRs
            cat results.txt >> report.md
            cml comment create report.md
            echo "## Data viz" >> report.md
            echo "![](./feature_importance.png 'Feature Importance')" >> report.md
            echo "![](./residuals.png 'Residuals')" >> report.md
            cml comment create report.md
            

What should be my next steps?

**Comment by 0x2b3bfa0** [comment] 2023-09-10 18:32
Duplicate of https://github.com/iterative/cml/issues/1422?

**Closed by 0x2b3bfa0** 2023-09-10 18:32 UTC
Labels: epic

**Comment by Sandy0002** [comment] 2023-09-10 18:36
No in this I am unable to pass images and getting Invalid url error. In that it was code integration error was there while this in this I am unable to pass images in the cml.yaml file.

**Comment by Sandy0002** [comment] 2023-09-10 18:37
Yes both are same sorry my bad.
