### ISSUE TITLE
Support for Bitbucket Cloud Pipelines self-hosted runners

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#646] opened 2021-07-06 11:49 UTC
BB is offering self hosted runners in beta.

**Comment by 0x2b3bfa0** [comment] 2021-07-06 13:18
Related to (or duplicate of) #140?

**Comment by DavidGOrtega** [comment] 2021-07-06 14:11
There are two BB

**Comment by 0x2b3bfa0** [comment] 2021-07-06 14:37
Then, this is just for Bitbucket Cloud Pipelines and not for Bitbucket Data Center, right? While I'd consider merging this issue with #140, it might be fine to keep both as long as they track different tasks.

See also the [official announcement](https://community.atlassian.com/t5/Bitbucket-Pipelines-articles/Bitbucket-Pipelines-Runners-is-now-in-open-beta/ba-p/1691022), the [documentation](https://support.atlassian.com/bitbucket-cloud/docs/runners) and [this guide](https://support.atlassian.com/bitbucket-cloud/docs/set-up-and-use-runners-for-linux)

**Comment by 0x2b3bfa0** [comment] 2021-09-07 12:21
Bitbucket officially supports self-hosted runners: https://iterativeai.slack.com/archives/C700E1B3Q/p1630099128011300

**Comment by Moynihan18** [comment] 2022-05-05 14:24
Received a request for this feature from a prospective customer. Has there been any movement on this?

**Closed** 2022-05-24 10:41 UTC
Labels: enhancement, p1-important, cml-runner, ci-new, ci-bitbucket

**Comment by 0x2b3bfa0** [comment] 2022-05-24 10:44
@Moynihan18, see #798
