### ISSUE TITLE
Bitbucket Server support estimated to arrive by mid 2021

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#1012] opened 2022-05-23 22:05 UTC
Can be read on README.
Not sure what do we need to support

**Comment by 0x2b3bfa0** [comment] 2022-05-23 23:10
Duplicate of https://github.com/iterative/cml/issues/140?

**Comment by DavidGOrtega** [comment] 2022-05-24 08:36
We support Bitbucket Cloud not server. 
We should discuss to support BB server and in any case we are not planning right now to support it.

**Comment by 0x2b3bfa0** [comment] 2022-05-26 13:22
This is a documentation issue; Bitbucket Server compatibility is tracked at #140

**Comment by DavidGOrtega** [comment] 2022-05-29 16:37
Why is this issue closed?
I still can see `Bitbucket Server support estimated to arrive by mid 2021.`
The biggest issue is the announcement for the last year

**Closed** 2022-05-29 16:37 UTC
Labels: documentation, invalid, ci-bitbucket

**Comment by DavidGOrtega** [comment] 2022-05-29 16:38
I see the PR now 🙏
