### ISSUE TITLE
Jobs getting cancelled with `runner status Job <job name> completed with result: Canceled`

### ISSUE THREAD

**Issue by jamt9000** [iterative/cml#840] opened 2021-12-09 21:20 UTC
Starting today all cml jobs (using github actions and AWS) are failing with `The self-hosted runner: cml-yfmmfzugyh lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.` (even when re-running jobs that previously succeeded - and the shutdown cause is `Client.UserInitiatedShutdown: User initiated shutdown`).

Checking the logs it seems like the job gets cancelled for some reason: `runner status Job <job name> completed with result: Canceled`

<img width="2965" alt="Screenshot 2021-12-09 at 20 25 23" src="https://user-images.githubusercontent.com/1186841/145475817-6adadb9a-b214-4be4-b2ef-81c2b7e58edf.png">

Whether this is due to cml or other github runner or aws issues I'm not sure, but there are various confusing messages in the logs that may be related:

```
runner status An error occurred Access denied. System:Serviceldentity;DDDDDDDD-DDDD-DDDD-DDDD-DDDDDDDDDDDD needs View permissions to perform the action.
\tFailed: Cannot destructure property 'id' of '(intermediate value)' as it is undefined.
```

Similar messages were reported in #676 and #345

**Comment by DavidGOrtega** [comment] 2021-12-10 09:51
👋 @jamt9000 my test repo seems to be working fine. Are you still in trouble or maybe it was a transient issue as #676 ?
I would need to see more logs. Please send them to me at david@iterative.ai

![image](https://user-images.githubusercontent.com/414967/145554018-26d5dd9b-77a2-416a-b0eb-29de8a71751f.png)

**Comment by dacbd** [comment] 2021-12-10 15:01
I'm 90% I encountered this before as well, the id is undefined error. I don't remember the resolution/I'll see if can find out where i encountered it as well.

**Comment by DavidGOrtega** [comment] 2021-12-10 16:19
We have also a couple of tickets with this... but its hard to reproduce

**Comment by jamt9000** [comment] 2021-12-10 22:02
Hello! So it was still failing earlier today, and I just tried a run to properly collect all the logs and now the issue isn't happening! So unfortunately the only logs I have are the screenshot above (taken quickly with ec2-instance-connect and `cat /var/log/syslog | grep cml` before the instance shut down).

One thing I did find is that the `Cannot destructure property 'id' of '(intermediate value)'` message appears even when it succeeds, so that seems to be unrelated. So it looks like `An error occurred Access denied. System:Serviceldentity;DDDDDDDD-DDDD-DDDD-DDDD-DDDDDDDDDDDD` is the only unusual one.

Not sure if there's much that can be done if it is transient and fixed now, so if you want to close the issue I can report if it comes back or if I find any other more clues.

**Comment by dacbd** [comment] 2021-12-10 22:30
Can you share the workflow yaml file?

**Comment by DavidGOrtega** [comment] 2021-12-13 09:17
@jamt9000 leave it open for a few days
🙏

**Comment by DavidGOrtega** [comment] 2021-12-23 14:03
Closed as we are unable to reproduce it again

**Closed by DavidGOrtega** 2021-12-23 14:03 UTC
Labels: p0-critical, cml-runner, cloud-aws
