### ISSUE TITLE
feature request: allow `cml-send-comment` to comment (and refresh) at the PR level

### ISSUE THREAD

**Issue by SaulAryehKohn** [iterative/cml#753] opened 2021-09-27 13:57 UTC
See this issue for reference: https://github.com/iterative/cml/issues/735

Attaching the `cml-send-comment` output to a given commit makes it fragile to rebase workflows, where those commits are orphaned and the CML comment lost. An alternative strategy would be to refresh a comment on the PR itself (done in [this action](https://github.com/EnricoMi/publish-unit-test-result-action), for example) which could maintain history and survive rebases.

**Comment by casperdcl** [comment] 2021-09-28 23:05
thanks - closing as duplicate of #735 after rewording

**Closed by casperdcl** 2021-09-28 23:05 UTC
