### ISSUE TITLE
support comment `--update` with default `GITHUB_TOKEN`

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml#1105] opened 2022-07-26 13:13 UTC
CML comment `--update` requires a user-defined PAT. Can we change the implementation to work with the default token too?

Would help a lot with user-friendliness of #1017.

- ref: https://cml.dev/doc/ref/send-comment#github
- discussions:
  + #888
  + https://github.com/iterative/cml.dev/pull/271#discussion_r925462960

**Comment by DavidGOrtega** [comment] 2022-07-29 11:57
I think that this limitation is a GH issue. `peter-evans/create-or-update-comment` only works with issue comment that are inherently different than commits comments. 
The link of both differs and indeed `peter-evans/create-or-update-comment` have another error when updating commits comments.

In example:
```
https://github.com/DavidGOrtega/fashion_mnist/commit/1ea79b838635928375cf459b978b6e1116cf13cd#commitcomment-79652370
```

```
Run peter-evans/create-or-update-comment@v2
  with:
    comment-id: 7965[2](https://github.com/DavidGOrtega/fashion_mnist/runs/7577465708?check_suite_focus=true#step:3:2)[3](https://github.com/DavidGOrtega/fashion_mnist/runs/7577465708?check_suite_focus=true#step:3:3)70
    body: echo Hi from Action!
  
    token: ***
  env:
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
Error: Not Found
```

While

```
https://github.com/DavidGOrtega/fashion_mnist/issues/37#issuecomment-1199153152
```
```
Run peter-evans/create-or-update-comment@v2
  with:
    comment-id: 119915315[2](https://github.com/DavidGOrtega/fashion_mnist/runs/7577674253?check_suite_focus=true#step:3:2)
    body: echo Hi from Action!
  
    token: ***
  env:
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
Updated comment id '119915[3](https://github.com/DavidGOrtega/fashion_mnist/runs/7577674253?check_suite_focus=true#step:3:3)1[5](https://github.com/DavidGOrtega/fashion_mnist/runs/7577674253?check_suite_focus=true#step:3:5)2'.
```

Want I want to say is that both comments are different in terms of API calls and it does not means anything that the actoin can update issue comments, the question is if thats possible.
Im testing the API via CURL

**Comment by DavidGOrtega** [comment] 2022-07-29 12:29
As I expected

```
curl -X PATCH \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: token ${GITHUB_TOKEN}" \
        https://api.github.com/repos/DavidGOrtega/fashion_mnist/comments/79652370 \
        -d '{"body":"HI CURL"}'
```
```
Run curl -X PATCH \
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
{
  "message": "Validation Failed",
  "errors": [
    {
100   3[13](https://github.com/DavidGOrtega/fashion_mnist/runs/7578675874?check_suite_focus=true#step:4:14)  100   295  100    [18](https://github.com/DavidGOrtega/fashion_mnist/runs/7578675874?check_suite_focus=true#step:4:19)    993     60 --:--:-- --:--:-- --:--:--  1053
      "resource": "CommitComment",
      "code": "custom",
      "field": "commit_id",
      "message": "commit_id has been locked"
    }
  ],
  "documentation_url": "https://docs.github.com/rest/reference/repos#update-a-commit-comment"
}
```

**Comment by dacbd** [comment] 2022-07-29 16:49
Again, espescially for the github api, comment on an issue differs from a comment on a commit. 
https://github.com/iterative/cml/blob/8aeac202da59a6170cfb76d96f310fc8c858f1c7/src/drivers/github.js#L102-L107

https://github.com/peter-evans/create-or-update-comment/blob/b95e16d2859ad843a14218d1028da5b2c4cbc4b4/index.js#L137-L142

**Comment by DavidGOrtega** [comment] 2022-07-29 21:05
@dacbd thats what I say. GH api behaves different with an issue or a commit comment. 
We are not doing anything wrong unless what we want is to be able to create ISSUE comments but CML was not originally thought for that.

**Comment by 0x2b3bfa0** [comment] 2022-07-29 21:18
See also https://github.com/iterative/cml.dev/commit/c7d27243d7449febf0655161f14aa897fb7d73bf

**Comment by 0x2b3bfa0** [comment] 2022-07-29 21:22
* Related to https://github.com/iterative/cml.dev/pull/253 in the documentation
* Probably duplicate of https://github.com/iterative/cml/issues/888

**Comment by 0x2b3bfa0** [comment] 2022-07-29 21:23
Can users solve this with custom [`permissions`](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token) perhaps?

**Comment by DavidGOrtega** [comment] 2022-07-29 21:27
> Can users solve this with custom [`permissions`](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token) perhaps?

Whats the difference of creating a PAT then? CML needs a PAT for the runner

**Comment by 0x2b3bfa0** [comment] 2022-07-29 21:33
It could be better for use cases where runners aren't needed. 🤷🏼‍♂️

**Comment by DavidGOrtega** [comment] 2022-07-29 21:42
But... there is an extra effort right ? I mean, you can not do this with a common `GITHUB_TOKEN` you need to sort out something else and probably you need the same permissions to modify it than to create a PAT... I do not fully understand the `GITHUB_TOKEN` when you can create a PAT

**Comment by DavidGOrtega** [comment] 2022-07-29 21:44
In any case there is nothing we can do to do on our side to fix `send-comment`.
Feel free to open it if makes sense

**Closed by DavidGOrtega** 2022-07-29 21:44 UTC
Labels: p1-important, cml-send-comment, ci-github, external-request

**Comment by casperdcl** [comment] 2022-08-05 14:24
To clarify, default (non-PAT) `GITHUB_TOKEN` is sufficient to:

location | creating comment | updating comment
---:|:---:|:---:
commit|:x:|:x:
PR|:x:|:x:
issue|:heavy_check_mark:|:heavy_check_mark:

From https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token it seems to imply `Default access
(permissive)` would convert all those :x:s into :heavy_check_mark:s.

**Comment by rogermparent** [comment] 2022-08-05 16:57
> Again, espescially for the github api, comment on an issue differs from a comment on a commit.

There's also [an action for creating commit comments](https://github.com/peter-evans/commit-comment/blob/8e589b3028a09fc36266b90ccf06b679ff74eab9/src/index.js#L32) that also doesn't seem to require a PAT.

**Comment by dacbd** [comment] 2022-08-05 23:48
> > Again, espescially for the github api, comment on an issue differs from a comment on a commit.
> 
> There's also [an action for creating commit comments](https://github.com/peter-evans/commit-comment/blob/8e589b3028a09fc36266b90ccf06b679ff74eab9/src/index.js#L32) that also doesn't seem to require a PAT.

Indeed @rogermparent it looks like you are correct and I would say that it appears `cml send-comment` works fine with the [default github token](https://github.com/dacbd/err/runs/7700426355?check_suite_focus=true)
