### ISSUE TITLE
`cml pr create .` fails if special symbols in the commited file path 

### ISSUE THREAD

**Issue by mnrozhkov** [iterative/cml#1289] opened 2022-12-16 15:49 UTC
`$ cml pr create --message="New simulation experiment" .` 

{"level":"error","message":"git add dvc.lock report.md run.sh outputs/sonicFoam_output.txt scalarTransportFoam/0/U sonicFoam/postProcessing/float_pressure.png ... outputs/sonicFoam/sonicFoam/3/uniform/functionObjects/functionObjectProperties.dvc\n\t\n\t/bin/sh: 1: Syntax error: \"(\" unexpected\n\n    at /usr/lib/node_modules/@dvcorg/cml/src/utils.js:35:27\n    at ChildProcess.exithandler (node:child_process:410:5)\n    at ChildProcess.emit (node:events:513:28)\n    at maybeClose (node:internal/child_process:1100:16)\n    at Socket.<anonymous> (node:internal/child_process:458:11)\n    at Socket.emit (node:events:513:28)\n    at Pipe.<anonymous> (node:net:301:12)"}

**Comment by 0x2b3bfa0** [comment] 2022-12-16 15:51
Duplicate of #1273, closed with #1275 (pending release, it seems)

**Closed** 2022-12-16 15:52 UTC
Labels: bug
