### ISSUE TITLE
cml pr trigger CI pipelines on GitLab

### ISSUE THREAD

**Issue by francesco086** [iterative/cml#1023] opened 2022-05-25 18:53 UTC
Following this message on Discord: https://discord.com/channels/485586884165107732/728693131557732403/978973993338044456

When the command `cml pr --merge dvc.lock` is executed as part of a GitLab CI pipeline, a new MR is created (as expected) and CI pipeline for that commit is triggered, which creates a new MR, etc. (loop of CI pipelines)
If you look at the [pipelines](https://gitlab.com/francesco-calcavecchia/titanic-demo-dvc-as-model-registry/-/pipelines) you will see several consecutive automatically triggered pipelines. Same if you look in the MRs (closed by me).

**Comment by francesco086** [comment] 2022-05-25 18:58
Forgot to mention, this is the branch where I am trying to make use of `cml pr`: https://gitlab.com/francesco-calcavecchia/titanic-demo-dvc-as-model-registry/-/tree/rely_solely_on_ci_for_dvc_repro

**Comment by DavidGOrtega** [comment] 2022-05-26 08:45
If we are adding `[ci skip]` gitlab might be not honouring it (again)?

**Comment by francesco086** [comment] 2022-05-27 16:38
Reading from [here](https://docs.gitlab.com/ee/user/project/push_options.html#push-options-for-gitlab-cicd): "Do not create a CI pipeline for the latest push. Only skips branch pipelines and not [merge request pipelines](https://docs.gitlab.com/ee/ci/pipelines/merge_request_pipelines.html)."

In my gitlab-ci I did not configure merge request pipelines, so it shouldn't be a problem.

**Comment by francesco086** [comment] 2022-05-27 18:05
I am observing that the CI pipelines are skipped if I omit the `--merge` option for `cml`. Curious about it, I checked in the code, and [here](https://github.com/iterative/cml/blob/master/src/cml.js#L465) found something interesting. Why do you append `skip ci` to the commit message only if not merge (or squash or rebase)? Maybe that is the issue?

**Comment by casperdcl** [comment] 2022-05-27 18:17
That is a bug :see_no_evil: :)

**Comment by francesco086** [comment] 2022-05-27 19:12
Ok, happy to see that I got it right :)

While waiting for your reply I was already checking into your further suggestion. In fact currently, even if the new branch does not activate the ci, once you merge it will! And that will create a new merge request etc.
So I was looking for a way to avoid that, and indeed if you set the title of the MR to include [skip ci] you should solve the problem.

**Comment by francesco086** [comment] 2022-05-27 19:13
It doesn’t seem very difficult to make these couple of changes, shall I create a MR for you? :)

**Comment by casperdcl** [comment] 2022-05-28 03:22
> once you merge it will!

That's typically intended behaviour (always test main). The workflow should be written to only create PRs/MRs from non-main branches (to avoid infinite PRs/MRs on `cml pr --merge`)

**Comment by DavidGOrtega** [comment] 2022-05-29 10:15
> It doesn’t seem very difficult to make these couple of changes, shall I create a MR for you? :)

That will be awesome!

**Comment by francesco086** [comment] 2022-05-30 12:48
Here you go: https://github.com/iterative/cml/pull/1035

PS: I would have preferred to first add tests and then make the changes, but I have never worked with js, and I don't have the time to figure out how to set up the development environment.

**Comment by francesco086** [comment] 2022-05-30 14:11
> Potential work-arounds:
> 
>     1. Make runs deterministic so rerunning with same hyperparams produces identical results (empty diff so no PR)
> 
>     2. Have `cml pr --merge` use default github-actions token (to not trigger another CI run). Not sure if there's a GitLab equivalent.
>        
>        * feature request: option to add `[skip ci]` to the PR title (afaik the PR title usually becomes the commit title upon merge)

Deterministic runs are of course desirable and should be the aim, but sometimes things go unexpectedly, so I would suggest no to rely on it, if it is not strictly necessary.

Regarding 2: I don't know about github-actions token, sorry. But I am quite sure that the MR title would solve. As it does not break anything, I don't see why not going that away, rather than having to set up extra stuff.

**Comment by francesco086** [comment] 2022-05-30 14:43
I take back my previous comment on MR title fixing the issue for GitLab :(

**Comment by francesco086** [comment] 2022-05-30 15:24
Checking again in the cml code and the GitLab API reference. I believe that one could avoid the problem mentioned above by adding [skip ci] to the commit message when merging the merge request, see [here](https://docs.gitlab.com/ee/api/merge_requests.html#merge-a-merge-request).

In practice, one could add the commit message with `[skip ci]` here: https://github.com/francesco086/cml/blob/33a54a5e8e4581122b76113f7b2c3dcddd4ecd55/src/drivers/gitlab.js#L267
or, probably better, add the skipci option once again, and in case append it to the commit message in the automerge...?

**Comment by DavidGOrtega** [comment] 2022-06-02 08:55
@francesco086 thanks for the contribution!!! ❤️ 
We have already merged it and will be available in the next release within a few hours!

**Comment by DavidGOrtega** [comment] 2022-06-02 08:56
closed via 
 - #1035

**Closed by DavidGOrtega** 2022-06-02 08:56 UTC
Labels: bug, cml-pr, ci-gitlab, external-request

**Comment by francesco086** [comment] 2022-06-02 12:14
> @francesco086 thanks for the contribution!!! ❤️
It was my pleasure :) thank you for the guidance!
