### ISSUE TITLE
Azure TFS and CML

### ISSUE THREAD

**Issue by RostyslavBryiovskyi** [iterative/cml#660] opened 2021-07-16 10:45 UTC
Hi all! Thanks for your great tools!:)
Can I use CML with Azure TFS somehow ?

**Comment by 0x2b3bfa0** [comment] 2021-07-16 19:14
👋🏼  Welcome, @RostyslavBryiovskyi! Would you like to use self-hosted Azure Pipelines runners from Azure DevOps Server (formerly **T**eam **F**oundation **S**erver) in conjunction with CML? If so, maybe we can merge this issue with #142

**Comment by RostyslavBryiovskyi** [comment] 2021-07-17 09:25
> 👋🏼 Welcome, @RostyslavBryiovskyi! Would you like to use self-hosted Azure Pipelines runners from Azure DevOps Server (formerly **T**eam **F**oundation **S**erver) in conjunction with CML? If so, maybe we can merge this issue with #142; it's on our roadmap.

@0x2b3bfa0, thankful for your quick reply!👍 Yeah, 
It would be great, and I'm looking forward to that😊
Could you please tell me, how long it will take ?

**Comment by 0x2b3bfa0** [comment] 2021-07-17 16:32
Duplicate of #142

**Closed by 0x2b3bfa0** 2021-07-17 16:32 UTC
Labels: duplicate, question

**Comment by 0x2b3bfa0** [comment] 2021-07-17 16:34
> _Could you please tell me, how long it will take?_

We haven't started to implement it yet. Please stay tuned to #142 for updates and, optionally, upvote it so we can keep track of the interested users.
