### ISSUE TITLE
`runner --cloud-metadata` parsing

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml#1104] opened 2022-07-26 07:12 UTC
From discord#cml/996742882058838057

- doesn't work: `cml runner ... --cloud-metadata "Work Area=TeamName"`
- doesn't work: `cml runner ... --cloud-metadata '"Work Area"="TeamName"'`
- works: `cml runner ... --cloud-metadata '"Work Area"=TeamName'`

**Comment by dacbd** [comment] 2022-07-26 17:27
Related:
- https://github.com/iterative/cml/pull/1100
- https://github.com/iterative/cml/issues/1099

**Comment by dacbd** [comment] 2022-07-26 18:34
Wrote test for these, fix it master via the linked above.

My caveat of the tag parsing may change behavior for users who fangaled the quote/whitespace issues, the example:
```
cml runner \
  --cloud=aws \
  --cloud-region=x \
  --cloud-metadata="condition one=KeyHasASpace" \
  --cloud-metadata='"condition two"="KeyAndValueAreWrappedWithQuotes"' \
  --cloud-metadata='"condition three"=KeyIsWrappedValueIsNot' \
  --cloud-type=t3.small
```
results with tags like:
```json
[
  {
    "Key": "\"condition three\"",
    "Value": "KeyIsWrappedValueIsNot"
  },
  {
    "Key": "Id",
    "Value": "iterative-17crj0i6rv6to"
  },
  {
    "Key": "Name",
    "Value": "cml-n467pqly04"
  },
  {
    "Key": "condition one",
    "Value": "KeyHasASpace"
  },
  {
    "Key": "condition two\"",
    "Value": "\"KeyAndValueAreWrappedWithQuotes"
  }
]
```

@iterative/cml  We should warn the discord user before the next release.

**Comment by 0x2b3bfa0** [comment] 2022-07-26 20:17
Duplicate of https://github.com/iterative/cml/issues/1099, and yes, warning that user would be nice.

**Closed by 0x2b3bfa0** 2022-07-26 20:17 UTC
Labels: bug, documentation, p1-important, external-request

**Comment by casperdcl** [comment] 2022-07-28 10:22
So we don't support quotes anymore?

**Comment by dacbd** [comment] 2022-07-29 20:37
> So we don't support quotes anymore?

depends on what you mean? I believe this properly supports quotes in a minimally required way. I think that the example highlights some oddities, yes, but I believe that the fangeling of those is dependent on yargs.

**Comment by casperdcl** [comment] 2022-08-05 14:10
> depends on what you mean?

I mean people currently have workflows that do `--cloud-metadata '"Work Area"=TeamName'`. And this https://github.com/iterative/cml/pull/1100 breaks things for said people? @0x2b3bfa0

**Comment by dacbd** [comment] 2022-08-05 17:38
It fixed the original where their workflows stopped working probably after some deps bump. So yes I agree this did break the workarounds which Is why I wanted to make sure we notified the user on discord.

To keep the correct parsing as well as the workaround parsing; I believe this would require upstream changes to yargs parsing so I don't believe it is feasible to support both.
