### ISSUE TITLE
CML seemingly fails to restart job after AWS Spot instances have been shut down 

### ISSUE THREAD

**Issue by thatGreekGuy96** [iterative/cml#650] opened 2021-07-08 10:51 UTC
Hey everyone, 
So I noticed a couple of days ago that CML now has new functionality that allows it to restart workflows if one or more AWS spot runners have been told to shut down. However this doesn't seem to be happening for me. 

A couple of details about our case: 
* Our cloud is AWS 
* We're (as far as i can tell) using the `latest` version of CML to deploy a bunch of runners as shown below. 
```
  deploy_runners:
    name: Deploy Cloud Instances
    needs: [setup_config]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
        with:
          version:  latest

      - name: "Deploy runner on EC2"
        shell: bash
        env:
          repo_token: ${{ secrets.ACCESS_TOKEN_CML }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_TESTING }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_TESTING }}
          CASE_NAME: ${{ matrix.case_name }}
          N_RUNNERS: ${{ fromJson(needs.setup_config.outputs.json_string).n_runners }}

        run: |
          for (( i=1; i<=N_RUNNERS; i++ ))
          do
            echo "Deploying runner ${i}"
            cml-runner \
            --cloud aws \
            --cloud-region eu-west-2 \
            --cloud-type=m \
            --cloud-hdd-size 100 \
            --cloud-spot \
            --labels=cml-runner &
          done
          wait
          echo "Deployed ${N_RUNNERS} runners."
```

* The job each runner runs does not use the CML images provided by iterative 
* The job that each runner runs has `continue-on-error` set to `False` (wondering whether that is interfering with cml?) 
```
  run_optimisation:
    continue-on-error: false
    strategy:
      matrix: ${{fromJson(needs.setup_config.outputs.json_string).matrix}}
      fail-fast: true

    runs-on: [self-hosted, "cml-runner"]
    container:
      image: python:3.8.10-slim
      volumes:
          - /dev/shm:/dev/shm
```

**Comment by 0x2b3bfa0** [comment] 2021-07-08 11:07
> ```bash
> for ((counter=0; counter<RUNNERS; counter++)); do
>   cml-runner --cloud ··· &
> done
> wait
> ```

Off-topic comment: this is an awesome trick! 💯

**Comment by 0x2b3bfa0** [comment] 2021-07-08 11:08
Maybe related to https://github.com/iterative/terraform-provider-iterative/issues/90? 🤔

**Comment by 0x2b3bfa0** [comment] 2021-07-08 11:15
Graceful shutdown issues are really fun to debug; see https://github.com/iterative/terraform-provider-iterative/issues/90 for an example. 🙃 Are you able to reproduce this issue when spawning a single runner?

```yaml
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - run: >-
            cml-runner
            --cloud aws
            --cloud-region eu-west-2
            --cloud-type=m
            --cloud-hdd-size 100
            --cloud-spot
            --labels=cml-runner
        env:
          REPO_TOKEN: ${{ secrets.ACCESS_TOKEN_CML }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_TESTING }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_TESTING }}
```

**Comment by thatGreekGuy96** [comment] 2021-07-08 14:27
This is what i got from the logs 
```
Warning: Permanently added '18.169.237.79' (ECDSA) to the list of known hosts.
-- Logs begin at Fri 2021-07-02 11:29:27 UTC. --
Jul 08 14:15:27 ip-172-31-1-181 systemd[1]: Starting cml service...
Jul 08 14:16:17 ip-172-31-1-181 cml.sh[2903]: Preparing workdir /tmp/tmp.cdIVPxU5h1/.cml/cml-bqc6j1s1wc...
Jul 08 14:16:17 ip-172-31-1-181 cml.sh[2903]: Launching github runner
Jul 08 14:16:37 ip-172-31-1-181 cml.sh[2903]: {"level":"info","date":"2021-07-08T14:16:37.027Z","repo":"https://github.com/continuum-industries/Pareto"}
Jul 08 14:16:37 ip-172-31-1-181 cml.sh[2903]: {"level":"info","date":"2021-07-08T14:16:37.027Z","repo":"https://github.com/continuum-industries/Pareto"}
Jul 08 14:16:37 ip-172-31-1-181 cml.sh[2903]: {"level":"info","date":"2021-07-08T14:16:37.461Z","repo":"https://github.com/continuum-industries/Pareto","status":"ready"}
Jul 08 14:21:37 ip-172-31-1-181 cml.sh[2903]: {"level":"info","status":"terminated"}
Jul 08 14:21:57 ip-172-31-1-181 cml.sh[2903]: Unregistering runner cml-nv4nzj9e1e...
Jul 08 14:22:41 ip-172-31-1-181 cml.sh[2903]:         Success
Jul 08 14:22:41 ip-172-31-1-181 cml.sh[2903]: {"level":"info","date":"2021-07-08T14:22:41.507Z","repo":"https://github.com/continuum-industries/Pareto"}
Jul 08 14:22:42 ip-172-31-1-181 cml.sh[2903]: iterative_cml_runner.runner: Refreshing state... [id=iterative-361txmhr4hxbv]
Jul 08 14:22:42 ip-172-31-1-181 cml.sh[2903]: Terraform used the selected providers to generate the following execution
Jul 08 14:22:42 ip-172-31-1-181 cml.sh[2903]: plan. Resource actions are indicated with the following symbols:
Jul 08 14:22:42 ip-172-31-1-181 cml.sh[2903]:   - destroy
Jul 08 14:22:42 ip-172-31-1-181 cml.sh[2903]:
Jul 08 14:22:42 ip-172-31-1-181 cml.sh[2903]: Terraform will perform the following actions:
Jul 08 14:22:42 ip-172-31-1-181 cml.sh[2903]:   # iterative_cml_runner.runner will be destroyed
Jul 08 14:22:42 ip-172-31-1-181 cml.sh[2903]:   - resource "iterative_cml_runner" "runner" {
Jul 08 14:22:42 ip-172-31-1-181 cml.sh[2903]:       - cloud             = "aws" -> null
Jul 08 14:22:42 ip-172-31-1-181 cml.sh[2903]:       - id                = "iterative-361txmhr4hxbv" -> null
Jul 08 14:22:42 ip-172-31-1-181 cml.sh[2903]:       - idle_timeout      = 300 -> null
Jul 08 14:22:42 ip-172-31-1-181 cml.sh[2903]:       - instance_hdd_size = 100 -> null
Jul 08 14:22:42 ip-172-31-1-181 cml.sh[2903]:       - name              = "cml-nv4nzj9e1e" -> null
Jul 08 14:22:42 ip-172-31-1-181 cml.sh[2903]:       - region            = "eu-west-2" -> null
Jul 08 14:22:42 ip-172-31-1-181 cml.sh[2903]:     }
Jul 08 14:22:42 ip-172-31-1-181 cml.sh[2903]: Plan: 0 to add, 0 to change, 1 to destroy.
Jul 08 14:22:42 ip-172-31-1-181 cml.sh[2903]: iterative_cml_runner.runner: Destroying... [id=iterative-361txmhr4hxbv]
Jul 08 14:22:42 ip-172-31-1-181 cml.sh[2903]: iterative_cml_runner.runner: Destruction complete after 0s
Jul 08 14:22:42 ip-172-31-1-181 cml.sh[2903]:
Jul 08 14:22:42 ip-172-31-1-181 cml.sh[2903]: Destroy complete! Resources: 1 destroyed.
Jul 08 14:22:42 ip-172-31-1-181 cml.sh[2903]: [3B blob data]
Jul 08 14:22:42 ip-172-31-1-181 systemd[1]: Started cml service.
Connection to 18.169.237.79 closed by remote host.
```

Interestingly though, the github actions job didn't crash! It's still running as far as I can tell. Is this the expected behaviour?

**Comment by thatGreekGuy96** [comment] 2021-07-08 15:13
I ran another test and now i'm a little confused: 
I followed your instructions again and got a similar log 
```
-- Logs begin at Fri 2021-07-02 11:29:27 UTC. --
Jul 08 15:00:55 ip-172-31-13-160 systemd[1]: Starting cml service...
Jul 08 15:01:44 ip-172-31-13-160 cml.sh[3077]: Preparing workdir /tmp/tmp.N15b61zzLK/.cml/cml-pxpkn2qtqm...
Jul 08 15:01:44 ip-172-31-13-160 cml.sh[3077]: Launching github runner
Jul 08 15:02:03 ip-172-31-13-160 cml.sh[3077]: {"level":"info","date":"2021-07-08T15:02:03.089Z","repo":"https://github.com/continuum-industries/Pareto"}
Jul 08 15:02:03 ip-172-31-13-160 cml.sh[3077]: {"level":"info","date":"2021-07-08T15:02:03.090Z","repo":"https://github.com/continuum-industries/Pareto"}
Jul 08 15:02:03 ip-172-31-13-160 cml.sh[3077]: {"level":"info","date":"2021-07-08T15:02:03.518Z","repo":"https://github.com/continuum-industries/Pareto","status":"ready"}
Jul 08 15:07:03 ip-172-31-13-160 cml.sh[3077]: {"level":"info","status":"terminated"}
Jul 08 15:07:23 ip-172-31-13-160 cml.sh[3077]: Unregistering runner cml-1f3wqycwzw...
Jul 08 15:08:08 ip-172-31-13-160 cml.sh[3077]:         Success
Jul 08 15:08:09 ip-172-31-13-160 cml.sh[3077]: iterative_cml_runner.runner: Refreshing state... [id=iterative-kwe52fn3orgf]
Jul 08 15:08:09 ip-172-31-13-160 cml.sh[3077]: Terraform used the selected providers to generate the following execution
Jul 08 15:08:09 ip-172-31-13-160 cml.sh[3077]: plan. Resource actions are indicated with the following symbols:
Jul 08 15:08:09 ip-172-31-13-160 cml.sh[3077]:   - destroy
Jul 08 15:08:09 ip-172-31-13-160 cml.sh[3077]:
Jul 08 15:08:09 ip-172-31-13-160 cml.sh[3077]: Terraform will perform the following actions:
Jul 08 15:08:09 ip-172-31-13-160 cml.sh[3077]:   # iterative_cml_runner.runner will be destroyed
Jul 08 15:08:09 ip-172-31-13-160 cml.sh[3077]:   - resource "iterative_cml_runner" "runner" {
Jul 08 15:08:09 ip-172-31-13-160 cml.sh[3077]:       - cloud             = "aws" -> null
Jul 08 15:08:09 ip-172-31-13-160 cml.sh[3077]:       - id                = "iterative-kwe52fn3orgf" -> null
Jul 08 15:08:09 ip-172-31-13-160 cml.sh[3077]:       - idle_timeout      = 300 -> null
Jul 08 15:08:09 ip-172-31-13-160 cml.sh[3077]:       - instance_hdd_size = 100 -> null
Jul 08 15:08:09 ip-172-31-13-160 cml.sh[3077]:       - name              = "cml-1f3wqycwzw" -> null
Jul 08 15:08:09 ip-172-31-13-160 cml.sh[3077]:       - region            = "eu-west-2" -> null
Jul 08 15:08:09 ip-172-31-13-160 cml.sh[3077]:     }
Jul 08 15:08:09 ip-172-31-13-160 cml.sh[3077]: Plan: 0 to add, 0 to change, 1 to destroy.
Jul 08 15:08:09 ip-172-31-13-160 cml.sh[3077]: iterative_cml_runner.runner: Destroying... [id=iterative-kwe52fn3orgf]
Jul 08 15:08:09 ip-172-31-13-160 cml.sh[3077]: iterative_cml_runner.runner: Destruction complete after 0s
Jul 08 15:08:09 ip-172-31-13-160 cml.sh[3077]:
Jul 08 15:08:09 ip-172-31-13-160 cml.sh[3077]: Destroy complete! Resources: 1 destroyed.
Jul 08 15:08:09 ip-172-31-13-160 cml.sh[3077]: [3B blob data]
Jul 08 15:08:09 ip-172-31-13-160 systemd[1]: Started cml service.
Connection to 18.169.238.177 closed by remote host.
```

On the EC2 console, I can see that the instance in question has indeed been terminated. 

HOWEVER, the spot request that created it still has a "fulfilled" status AND the github actions job is still running... 

I hope this makes more sense to you than it does to me!

**Comment by 0x2b3bfa0** [comment] 2021-07-08 19:36
<blockquote><i><p>On the EC2 console, I can see that the instance in question has indeed been terminated.</p><p>HOWEVER, the spot request that created it still has a "fulfilled" status AND the github actions job is still running...</p><p>I hope this makes more sense to you than it does to me!</p></i><p><i>Update: After about 5 minutes, the spot request was marked as terminated-by-user, </i>[...]</p></blockquote>

As per the [spot request status](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-request-status.html) reference, the state transitions you describe seem to match the expected behavior. I don't know if those actions should take several minutes, though.

> [...] _but the github actions job is still running... 

Is it just the status, or have you checked if the job is alive? If you aren't sure, you can replace the `cat` command in the last line of https://github.com/iterative/cml/issues/650#issuecomment-876352433 with the following:

```bash
while true; do echo $((++counter)); sleep 1; done
```

If you still see the count progressing after the spot instance enters the `terminated-by-user` state, it would mean that either the old instance is still alive or everything worked as expected and CML restarted the job without you noticing.

> _As far as I can tell, no new spot requests have been made._

In this case, can you please retrieve a new log using the following step instead of the `- uses: iterative/setup-cml@v1` one?

```yaml
- run: |
    sudo npm config set user 0
    sudo npm install --global git+https://github.com/iterative/cml#debug-long-job
```

**Comment by thatGreekGuy96** [comment] 2021-07-08 22:01
So actually that was my bad, i was running the jobs on the wrong runner :/ I managed to set the job correctly afterwards and I've been waiting for it to fail. Unfortunately, aws spot did not shut the instance down. It did however reach the maximum runtime of 6 hours. Here are the logs 
```
-- Logs begin at Fri 2021-07-02 11:29:27 UTC. --
Jul 08 15:54:01 ip-172-31-10-233 systemd[1]: Starting cml service...
Jul 08 15:54:48 ip-172-31-10-233 cml.sh[3089]: Preparing workdir /tmp/tmp.ulnFhn9cxz/.cml/cml-rlj3ki1iw7...
Jul 08 15:54:48 ip-172-31-10-233 cml.sh[3089]: Launching github runner
Jul 08 15:55:06 ip-172-31-10-233 cml.sh[3089]: {"level":"info","date":"2021-07-08T15:55:06.759Z","repo":"https://github.com/continuum-industries/Pareto"}
Jul 08 15:55:06 ip-172-31-10-233 cml.sh[3089]: {"level":"info","date":"2021-07-08T15:55:06.759Z","repo":"https://github.com/continuum-industries/Pareto"}
Jul 08 15:55:07 ip-172-31-10-233 cml.sh[3089]: {"level":"info","date":"2021-07-08T15:55:07.185Z","repo":"https://github.com/continuum-industries/Pareto","status":"ready"}
Jul 08 15:55:23 ip-172-31-10-233 cml.sh[3089]: {"level":"info","date":"2021-07-08T15:55:22.988Z","repo":"https://github.com/continuum-industries/Pareto","job":3020940409,"status":"job_started"}
Jul 08 21:55:37 ip-172-31-10-233 cml.sh[3089]: {"level":"error","date":"2021-07-08T21:55:37.311Z","repo":"https://github.com/continuum-industries/Pareto","job":"","status":"job_ended","success":false}
```

The workflow doesn't get restarted after this I''m afraid... 
I'll run another test to see if i AWS will shut down the spot instance

**Comment by DavidGOrtega** [comment] 2021-07-09 09:11
> Unfortunately, aws spot did not shut the instance down. It did however reach the maximum runtime of 6 hours. Here are the logs

🤔 Our code is expecting the spot instances to be terminated. After those 6hours the spot instance is going to be still alive?

**Comment by DavidGOrtega** [comment] 2021-07-09 09:37
Eureka! 

I got you!
As you say spot instance is not terminated.Here the guilty is the job timeout in GH.

You have to setup it as 

```yaml
run_optimisation:
   timeout-minutes: 10000
    continue-on-error: false
    strategy:
      matrix: ${{fromJson(needs.setup_config.outputs.json_string).matrix}}
      fail-fast: true

    runs-on: [self-hosted, "cml-runner"]
    container:
      image: python:3.8.10-slim
      volumes:
          - /dev/shm:/dev/shm
```

As far as  can tell by MY experience:

 - workflow limit is meant to be at most 72H (our runner handles this ;) ) however if you specify the job limit above those 72 hours that limit disappears (probably a GH bug)
  - Never setup the timeout-minutes in a step. Opposed to GH docs it WONT work. Setting the limit to 6 hours again

**Comment by DavidGOrtega** [comment] 2021-07-09 09:40
Our runner only restarts in to scenarios:
 - the machine is being destroyed and there are still jobs
 - the 72 hours GH limit that will restart the workflow even if you specify a greater ```timeout-minutes``` making the 72h limit invalid. We still do this (opposed to my experience) because I believe that it is a bug that should be fixed at any point breaking the runner again. The only drawback is that you might loose an epoch while we restart because of the 72 hours limiit.

**Comment by thatGreekGuy96** [comment] 2021-07-09 10:26
Ah ok, i thought the timeout referred to the 360 minutes that a job can run on. 

In any case, I managed to replicate the issue. This is what i see on the logs 
```
-- Logs begin at Fri 2021-07-02 11:29:27 UTC. --
Jul 09 08:21:43 ip-172-31-14-78 systemd[1]: Started cml.service.
Jul 09 08:22:36 ip-172-31-14-78 cml.sh[3252]: Preparing workdir /tmp/tmp.ePH7ZEdNZl/.cml/cml-8qy3d9e8w7...
Jul 09 08:22:36 ip-172-31-14-78 cml.sh[3252]: Launching github runner
Jul 09 08:22:58 ip-172-31-14-78 cml.sh[3252]: {"level":"info","date":"2021-07-09T08:22:58.295Z","repo":"https://github.com/continuum-industries/Pareto"}
Jul 09 08:22:58 ip-172-31-14-78 cml.sh[3252]: {"level":"info","date":"2021-07-09T08:22:58.296Z","repo":"https://github.com/continuum-industries/Pareto"}
Jul 09 08:22:58 ip-172-31-14-78 cml.sh[3252]: {"level":"info","date":"2021-07-09T08:22:58.693Z","repo":"https://github.com/continuum-industries/Pareto","status":"ready"}
Jul 09 08:23:10 ip-172-31-14-78 cml.sh[3252]: {"level":"info","date":"2021-07-09T08:23:09.417Z","repo":"https://github.com/continuum-industries/Pareto","job":3023764478,"status":"job_started"}

client_loop: send disconnect: Broken pipe
```

On the github the job failed because the runner shut down due to spot killing it. On the AWS side i can also confirm that the spot instance was terminated with `instance-terminated-no-capacity` . However the workflow did not restart.

**Comment by DavidGOrtega** [comment] 2021-07-09 11:29
> Ah ok, i thought the timeout referred to the 360 minutes that a job can run on.

I do not fully understand this. Could you please elaborate?

> On the github the job failed because the runner shut down due to spot killing it. On the AWS side i can also confirm that the spot instance was terminated with instance-terminated-no-capacity . However the workflow did not restart.

can you try to terminate the instance manually in the console and check that it restarts? If so, seems that spot instances might be killing  instances with other method than terminate.

**Comment by DavidGOrtega** [comment] 2021-07-09 12:00
And I can confirm that they use also terminate and the workflow restarts 🤔

**Comment by thatGreekGuy96** [comment] 2021-07-12 08:20
Terminating the instance manually gives me this in the logs: 
```
-- Logs begin at Fri 2021-07-02 11:29:27 UTC. --
Jul 12 08:15:19 ip-172-31-7-6 systemd[1]: Started cml.service.
Jul 12 08:16:01 ip-172-31-7-6 cml.sh[3301]: Preparing workdir /tmp/tmp.LCA5ec7MoW/.cml/cml-61sqgx299o...
Jul 12 08:16:01 ip-172-31-7-6 cml.sh[3301]: Launching github runner
Jul 12 08:16:27 ip-172-31-7-6 cml.sh[3301]: {"level":"info","date":"2021-07-12T08:16:27.131Z","repo":"https://github.com/continuum-industries/Pareto"}
Jul 12 08:16:27 ip-172-31-7-6 cml.sh[3301]: {"level":"info","date":"2021-07-12T08:16:27.132Z","repo":"https://github.com/continuum-industries/Pareto"}
Jul 12 08:16:28 ip-172-31-7-6 cml.sh[3301]: {"level":"info","date":"2021-07-12T08:16:28.324Z","repo":"https://github.com/continuum-industries/Pareto","status":"ready"}
Jul 12 08:16:40 ip-172-31-7-6 cml.sh[3301]: {"level":"info","date":"2021-07-12T08:16:40.023Z","repo":"https://github.com/continuum-industries/Pareto","job":3044570052,"status":"job_started"}
Connection to 18.133.187.34 closed by remote host.
```

But I can confirm that the github worklow restarts!

**Comment by DavidGOrtega** [comment] 2021-07-20 10:21
@thatGreekGuy96 I have setup a spot termination notification handler in #653

**Closed** 2021-07-20 16:20 UTC
Labels: cml-runner, p0-critical

**Comment by thatGreekGuy96** [comment] 2021-07-20 17:49
Awesome, thank you!
