### ISSUE TITLE
Provision instance in specific AWS zone

### ISSUE THREAD

**Issue by martbert** [iterative/cml#459] opened 2021-03-23 14:54 UTC
Hi,

CML looks very promising for allowing easy MLOps. I've been playing around with it and stumbled upon a small issue. Say I want to run a job on a p3.2xlarge (AWS) instance on AWS in the us-east-1 region. Turns out those instances are not available in all zones. Hence when the runner tries to provision the said type of instance in us-east-1c, it fails. Would it be possible to consider the support of zones?

Cheers!

**Comment by DavidGOrtega** [comment] 2021-04-13 12:25
👋 @martbert 
Yes we are actually contemplating it and actually there is another ticket regarding this.
Will be resolved soon. I will ping you.

**Comment by 0x2b3bfa0** [comment] 2021-12-01 20:26
@DavidGOrtega, can you please link to the issue this is a duplicate of? 

What if we allow specifying both regions and availability zones using `cml runner --cloud-region=<value>` or, more precisely, the `region` attribute in the provider?

Both `us-east-1` and `us-east-1c` would be valid values. When a native region string ends with a lowercase letter, we can extract both values and use them accordingly.

Adding a `availability-zone` filter condition [here](https://github.com/iterative/terraform-provider-iterative/blob/550c698677b94644a80fa019fab6f62b26787543/iterative/aws/provider.go#L192-L197) should do the trick. The [same](https://github.com/iterative/terraform-provider-iterative/blob/550c698677b94644a80fa019fab6f62b26787543/task/aws/resources/data_source_default_vpc_subnet.go#L31-L36) goes for the task resource.

**Comment by dacbd** [comment] 2021-12-01 22:48
I believe that https://github.com/iterative/cml/issues/814 and https://github.com/iterative/cml/issues/795 are related since the fix would involve the same chunk of code, I intended to get a PR for in around the weekend.

**Closed** 2021-12-18 15:57 UTC
Labels: duplicate, cml-runner
