### ISSUE TITLE
GCP VM instance not terminating after timeout

### ISSUE THREAD

**Issue by eemelipa** [iterative/cml#834] opened 2021-12-04 19:17 UTC
Similar issue to https://github.com/iterative/cml/issues/678

I'm starting a self hosted runner via Gitlab CICD to GCP:

```
deploy-runner:
  stage: start runner
  image: iterativeai/cml:0-dvc2-base1
  resource_group: all
  script:
    - cml runner --cloud=gcp --cloud-region=eu-north --cloud-type=c2-standard-4 --labels=cml-runner --reuse --idle-timeout 600
```

After the timeout the VM instance is not shutting down.

`journalctl --unit cml --no-pager` command shows

```
-- Logs begin at Sat 2021-12-04 18:40:23 UTC, end at Sat 2021-12-04 19:02:12 UTC. --
Dec 04 18:43:29 cml-4ejd6b8lzc systemd[1]: Started cml.service.
Dec 04 18:43:37 cml-4ejd6b8lzc cml.sh[17099]: {"level":"info","message":"Preparing workdir /tmp/tmp.rtgpwktKf5/.cml/cml-4ejd6b8lzc..."}
Dec 04 18:43:37 cml-4ejd6b8lzc cml.sh[17099]: {"level":"info","message":"Launching gitlab runner"}
Dec 04 18:43:41 cml-4ejd6b8lzc cml.sh[17099]: {"level":"warn","message":"SpotNotifier can not be started."}
Dec 04 18:43:41 cml-4ejd6b8lzc cml.sh[17099]: {"date":"2021-12-04T18:43:41.453Z","level":"info","message":"runner status","repo":"https://gitlab.com/common-kube/ml"}
Dec 04 18:43:41 cml-4ejd6b8lzc cml.sh[17099]: {"date":"2021-12-04T18:43:41.454Z","level":"info","message":"runner status","repo":"https://gitlab.com/common-kube/ml","status":"ready"}
Dec 04 18:43:42 cml-4ejd6b8lzc cml.sh[17099]: {"date":"2021-12-04T18:43:42.276Z","job":1850241152,"level":"info","message":"runner status","repo":"https://gitlab.com/common-kube/ml","status":"job_started"}
Dec 04 18:44:38 cml-4ejd6b8lzc cml.sh[17099]: {"date":"2021-12-04T18:44:38.904Z","level":"info","message":"runner status","repo":"https://gitlab.com/common-kube/ml"}
Dec 04 18:45:46 cml-4ejd6b8lzc cml.sh[17099]: {"date":"2021-12-04T18:45:46.363Z","job":1850241152,"level":"info","message":"runner status","repo":"https://gitlab.com/common-kube/ml"}
Dec 04 18:45:49 cml-4ejd6b8lzc cml.sh[17099]: {"date":"2021-12-04T18:45:46.363Z","job":1850241152,"level":"info","message":"runner status","repo":"https://gitlab.com/common-kube/ml"}
Dec 04 18:46:26 cml-4ejd6b8lzc cml.sh[17099]: {"date":"2021-12-04T18:46:26.303Z","job":1850241152,"level":"info","message":"runner status","repo":"https://gitlab.com/common-kube/ml","status":"job_ended","success":false}
Dec 04 18:46:26 cml-4ejd6b8lzc cml.sh[17099]: {"date":"2021-12-04T18:46:26.649Z","job":1850241152,"level":"info","message":"runner status","repo":"https://gitlab.com/common-kube/ml"}
Dec 04 18:46:26 cml-4ejd6b8lzc cml.sh[17099]: {"date":"2021-12-04T18:46:26.952Z","job":1850241152,"level":"info","message":"runner status","repo":"https://gitlab.com/common-kube/ml"}
Dec 04 18:46:26 cml-4ejd6b8lzc cml.sh[17099]: {"date":"2021-12-04T18:46:26.953Z","level":"info","message":"runner status","repo":"https://gitlab.com/common-kube/ml"}
Dec 04 18:56:28 cml-4ejd6b8lzc cml.sh[17099]: {"level":"info","message":"runner status","reason":"timeout:600","status":"terminated"}
Dec 04 18:56:28 cml-4ejd6b8lzc cml.sh[17099]: {"level":"info","message":"waiting 20 seconds before exiting..."}
Dec 04 18:56:48 cml-4ejd6b8lzc cml.sh[17099]: {"level":"info","message":"Unregistering runner cml-4ejd6b8lzc..."}
Dec 04 18:56:49 cml-4ejd6b8lzc cml.sh[17099]: {"level":"info","message":"\tSuccess"}
Dec 04 18:56:50 cml-4ejd6b8lzc systemd[1]: cml.service: Succeeded.
```

The runner picks up a job correctly and the runner deregisters itself from the Gitlab project. The VM instance just does not shutdown.

On Azure similar config worked ok and the instances were shutting down

**Comment by eemelipa** [comment] 2021-12-04 19:50
Tried in different region and instance type: `--cloud-region=europe-west1-b --cloud-type=n1-standard-1` but that did not help

**Comment by DavidGOrtega** [comment] 2021-12-06 11:49
@eemelipa thanks a lot for the issue.

**Comment by dacbd** [comment] 2021-12-10 22:28
hmm 🤔 the opposite of mine https://github.com/iterative/cml/issues/808

@eemelipa can you post a screenshot for me? After you run your pipeline go to the GCP dashboard for the project then the Activity tab and take a screenshot?

If it's in a busy project that has other stuff, search for the "Logs Explorer" and narrow the time to when your pipeline ran, and look for any "severity" high than "notice"

**Comment by eemelipa** [comment] 2021-12-11 09:33
![image](https://user-images.githubusercontent.com/3244050/145671683-c310c07f-36f5-40f4-8280-fc4c551c7a31.png)

@dacbd  here's the screenshot ^ There weren't any warn/error logs 🤔  The bootCounter: 2 latebootreportevent seems to happen correctly at 5min mark which was the idle-timeout in this case. I don't know if the logs are missing any rows though

The credentials have "Compute Admin" privilege

**Comment by dacbd** [comment] 2021-12-12 17:10
@eemelipa there should be some firewall/network API calls. When I had the teardowns fail these calls failed and so the instance remained.

**Comment by eemelipa** [comment] 2021-12-12 19:04
> @eemelipa there should be some firewall/network API calls. When I had the teardowns fail these calls failed and so the instance remained.

Ok, I adjusted the log filtering and now the firewall inserts are visible:

![image](https://user-images.githubusercontent.com/3244050/145725115-ec2bf80b-6b75-401e-b8db-a73dbc74d77b.png)

No errors/warnings though. Any thoughts on what to look for next? I tried giving the service account owner access to the project (i.e., all privileges) but that didn't help

**Comment by dacbd** [comment] 2021-12-12 19:21
An error here would have made this an easy fix 😞 

There is something more complicated going on, "Compute Admin" is a sufficient role.

**Comment by dacbd** [comment] 2021-12-12 19:46
I'm not sure how much help I can provide without digging into the setup more, or building a custom cml image with more debug logging for the terraform provider

Here you can see a full successful logging lifecycle in gcp
![image](https://user-images.githubusercontent.com/1105843/145726530-7eb229df-9f5e-45b1-841e-9fbdf4d6ee76.png)

**Comment by dacbd** [comment] 2021-12-12 19:59
We might be able to get more info out of `journalctl` by adding a start-up script that creates a custom environment over-ride for the cml.service `/etc/systemd/system/cml.service.d/debug.conf`

I think something like this should work:
debug.conf
```
[Service]
Environment="TF_LOG=DEBUG"
```

**Comment by eemelipa** [comment] 2021-12-13 22:35
Spend good time fiddling manually on the VM instance and got a step forward

Looks like the problem is that the CML VM instance did not get any GCP service account:

![image](https://user-images.githubusercontent.com/3244050/145899859-e43e5499-1be4-4c07-9815-fa982c160bba.png)


When I put that in place manually and restarted the instance things worked! The instance got deleted after the idle-timeout.

Sounds like something should fail if the instance does not have a service account. Here's couple options that came to my mind (obviously you guys know better what's under the hood):
1. The iterative terraform provider should fail when fetching credentials in case service account is not in place (maybe somewhere here https://github.com/iterative/terraform-provider-iterative/blob/550c698677b94644a80fa019fab6f62b26787543/iterative/gcp/provider.go#L295)
2. The GCP service account is specified with `--cloud-permission-set` cml cli argument. If the `--cloud=gcp` but the service account is missing then the `cml runner` command should fail


So missing service account is one problem and we seem to also have a second problem. When I give service account to cml runner command it creates the VM instance correctly with the account but it does not give correct Cloud API access scopes:

![image](https://user-images.githubusercontent.com/3244050/145897838-8d084894-f6d7-41f6-8746-cac1e372a36c.png)

When I gave manually the API scopes the idle-timeout deletion worked ok. Sounds like some changes might be needed to the CML instance creation

**Comment by dacbd** [comment] 2021-12-13 23:19
Hmm, it sounds like some documentation clarification might be required?

Under the hood, `cml runner` adds the `GOOGLE_APPLICATION_CREDENTIALS_DATA` that cml was invoked with into the systemd service unit as those should be the credentials used for the creation of the instance and thus also should be used for the teardown of the instance.

The `--cloud-permission-set` takes (in GCP's case) the service account email to attach to the instance, the intent behind that is for the application or ML model to use to access other services from the cloud provider like s3/object storage.

Are you saying it looks like terraform tried to use those (the `--cloud-permission-set`) creds instead of the original `cml runner` ones? That is definitely not intended.

This should be easy for me to reproduce and I'll try to get it fixed soon, if you are on discord and willing to test out a patch I can let you know when I have something working (dabarnes on discord)

**Comment by dacbd** [comment] 2021-12-13 23:34
Can you share more of the yml from gitlab-ci?

I think I misunderstood some of your last reply.

Can you share the permissions list or GCP managed role for the service account whose key should be set in the `GOOGLE_APPLICATION_CREDENTIALS_DATA` environment variable when you invoke your `cml runner` command and the same for the one you are trying to set with the `--cloud-permission-set` ?

Also, cat out the `/etc/systemd/system/cml.service` file and ***be sure to check and redact any sensitive values that might be there***

**Comment by dacbd** [comment] 2021-12-14 23:10
Can be closed with TPI fix: https://github.com/iterative/terraform-provider-iterative/pull/333

**Comment by casperdcl** [comment] 2021-12-16 13:33
fixed by https://github.com/iterative/terraform-provider-iterative/pull/333; thanks @dacbd

**Closed by casperdcl** 2021-12-16 13:33 UTC
Labels: p0-critical, cml-runner, cloud-gcp

**Comment by hopeai** [comment] 2023-06-09 12:02
Facing this issue with  cml v0.19.0

I'm starting GCP instance using the following command inside a docker container which uses `iterativeai/cml:latest` image in a buildkite pipeline. I also share `GOOGLE_APPLICATION_CREDENTIALS_DATA` as environment variable, it starts and register self-hosted runner with out any problem.

Configure gcloud:
```
echo "$GOOGLE_APPLICATION_CREDENTIALS_DATA" >~/gcloud-service-account-key.json
gcloud -q auth activate-service-account --key-file ~/gcloud-service-account-key.json
gcloud -q config set project PROJECT
gcloud -q auth configure-docker
```
Run cml runner launch
```
cml runner launch \
--cloud=gcp \
--cloud-region=us-central1-a \
--cloud-type=m+t4	 \
--name="$CML_RUNNER_NAME" \
--labels=gcp-snapshot-creation \
--token="$BUILDKITE_GITHUB_TOKEN" \
--repo=https://github.com/ORG/REPO.git \
--cloud-hdd-size=60 \
--idle-timeout=120
```

However, after idle-timeout passes GCP VM doesn't terminate. The output of `journalctl --unit cml --no-pager` is as follows:
```
-- Logs begin at Fri 2023-06-09 10:33:16 UTC, end at Fri 2023-06-09 11:28:01 UTC. --
Jun 09 10:38:43 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 systemd[1]: Started cml.service.
Jun 09 10:38:44 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 cml.sh[40734]: {"level":"info","message":"POST /repos/ORG/REPO/actions/runners/registration-token - 201 in 287ms"}
Jun 09 10:38:44 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 cml.sh[40734]: {"level":"info","message":"GET /repos/ORG/REPO/actions/runners?per_page=100 - 200 in 234ms"}
Jun 09 10:38:44 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 cml.sh[40734]: {"level":"warn","message":"Github Actions timeout has been updated from 72h to 35 days. Update your workflow accordingly to be able to restart it automatically."}
Jun 09 10:38:44 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 cml.sh[40734]: {"level":"info","message":"Preparing workdir /tmp/tmp.SpVQaKjpnL/.cml/cml-REPO-snapshot-t4-wi89wx1i-4src3nn4..."}
Jun 09 10:38:44 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 cml.sh[40734]: {"level":"info","message":"Launching github runner"}
Jun 09 10:38:48 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 cml.sh[40734]: {"level":"info","message":"Terraform 1.4.6"}
Jun 09 10:38:48 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 cml.sh[40734]: {"level":"info","message":"Plan: 0 to add, 0 to change, 0 to destroy."}
Jun 09 10:38:48 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 cml.sh[40734]: {"level":"info","message":"Apply complete! Resources: 0 added, 0 changed, 0 destroyed."}
Jun 09 10:38:48 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 cml.sh[40734]: {"level":"info","message":"Outputs: 0"}
Jun 09 10:38:48 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 cml.sh[40734]: {"level":"info","message":"Connected to acpid service."}
Jun 09 10:38:58 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 cml.sh[40734]: {"level":"info","message":"POST /repos/ORG/REPO/actions/runners/registration-token - 201 in 307ms"}
Jun 09 10:39:01 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 cml.sh[40734]: {"date":"2023-06-09T10:39:01.672Z","level":"info","message":"runner status","repo":"https://github.com/ORG/REPO","status":"ready"}
Jun 09 10:39:20 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 cml.sh[40734]: {"date":"2023-06-09T10:39:20.270Z","level":"info","message":"runner status","repo":"https://github.com/ORG/REPO","status":"job_started"}
Jun 09 10:43:40 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 sudo[41348]:     root : TTY=unknown ; PWD=/tmp/tmp.SpVQaKjpnL/.cml/cml-REPO-snapshot-t4-wi89wx1i-4src3nn4/_work/REPO/REPO ; USER=root ; COMMAND=/usr/bin/mkdir -p /data
Jun 09 10:43:40 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 sudo[41348]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jun 09 10:43:40 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 sudo[41348]: pam_unix(sudo:session): session closed for user root
Jun 09 10:43:40 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 sudo[41350]:     root : TTY=unknown ; PWD=/tmp/tmp.SpVQaKjpnL/.cml/cml-REPO-snapshot-t4-wi89wx1i-4src3nn4/_work/REPO/REPO ; USER=root ; COMMAND=/usr/bin/mount /dev/sdb1 /data
Jun 09 10:43:40 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 sudo[41350]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jun 09 10:43:41 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 sudo[41350]: pam_unix(sudo:session): session closed for user root
Jun 09 10:43:41 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 sudo[41356]:     root : TTY=unknown ; PWD=/tmp/tmp.SpVQaKjpnL/.cml/cml-REPO-snapshot-t4-wi89wx1i-4src3nn4/_work/REPO/REPO ; USER=root ; COMMAND=/usr/bin/lsblk
Jun 09 10:43:41 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 sudo[41356]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jun 09 10:43:41 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 sudo[41356]: pam_unix(sudo:session): session closed for user root
Jun 09 10:43:44 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 cml.sh[40734]: {"date":"2023-06-09T10:43:44.840Z","level":"info","message":"runner status","repo":"https://github.com/ORG/REPO","status":"job_ended","success":true}
Jun 09 10:43:47 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 cml.sh[40734]: {"date":"2023-06-09T10:43:47.170Z","level":"info","message":"runner status","repo":"https://github.com/ORG/REPO","status":"job_started"}
Jun 09 11:02:44 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 cml.sh[40734]: {"date":"2023-06-09T11:02:44.588Z","level":"info","message":"runner status","repo":"https://github.com/ORG/REPO","status":"job_ended","success":true}
Jun 09 11:04:45 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 cml.sh[40734]: {"level":"info","message":"Unregistering runner cml-REPO-snapshot-t4-wi89wx1i-4src3nn4..."}
Jun 09 11:04:45 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 cml.sh[40734]: {"level":"info","message":"GET /repos/ORG/REPO/actions/runners?per_page=100 - 403 in 159ms"}
Jun 09 11:04:45 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 cml.sh[40734]: {"level":"info","message":"Retrying because of rate limit in 990 seconds"}
Jun 09 11:21:15 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 cml.sh[40734]: {"level":"info","message":"GET /repos/ORG/REPO/actions/runners?per_page=100 - 200 in 260ms"}
Jun 09 11:21:15 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 cml.sh[40734]: {"level":"info","message":"DELETE /repos/ORG/REPO/actions/runners/314 - 204 in 371ms"}
Jun 09 11:21:15 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 cml.sh[40734]: {"level":"info","message":"\tSuccess"}
Jun 09 11:21:15 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 cml.sh[40734]: {"level":"info","message":"Waiting 10 seconds to destroy"}
Jun 09 11:21:26 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 cml.sh[40734]: {"level":"info","message":"runner status","reason":"timeout:120","status":"terminated"}
Jun 09 11:21:26 cml-REPO-snapshot-t4-wi89wx1i-4src3nn4 systemd[1]: cml.service: Succeeded

```
I am not facing any issue with aws ec2 instances and those terminate after idle-timeout.
