### ISSUE TITLE
cml-runner times out when trying to check status of spawned instance

### ISSUE THREAD

**Issue by thatGreekGuy96** [iterative/cml#536] opened 2021-05-19 09:50 UTC
Hey everyone! 
We've been using `cml` for a bout a month now to deploy ec2 runners and run tests on them. We have run into a weird problem today where the deploy runners command times out because it cannot talk to the ec2 instances. I'm attaching the logs below. 

As far as I can tell the runners are getting deployed and have public ipv4 addresses assigned to them. However, when I try to connect using EC2 connect i get this error: 

<img width="661" alt="image" src="https://user-images.githubusercontent.com/42438403/118791674-d696b580-b88e-11eb-958b-8b59585ddb4d.png">

Does someone know what could be going on here? Has something been updated on the cml side that we should know about? Any help would be greatly appreciated! 

[2_Deploy Cloud Instances (1).txt](https://github.com/iterative/cml/files/6507612/2_Deploy.Cloud.Instances.1.txt)

**Comment by 0x2b3bfa0** [comment] 2021-05-19 09:55
```console
May 19 08:25:12 ip-172-31-14-60 systemd[1]: Starting cml service...
May 19 08:25:12 ip-172-31-14-60 cml.sh[3019]: /usr/bin/cml.sh: 14: exec: cml-runner: not found
May 19 08:25:12 ip-172-31-14-60 systemd[1]: cml.service: Main process exited, code=exited, status=127/n/a
May 19 08:25:12 ip-172-31-14-60 systemd[1]: cml.service: Failed with result 'exit-code'.
May 19 08:25:12 ip-172-31-14-60 systemd[1]: Failed to start cml service.
May 19 08:25:12 ip-172-31-14-60 cloud-init[2049]: Job for cml.service failed because the control process exited with error code.
```

**Comment by 0x2b3bfa0** [comment] 2021-05-19 09:59
👋🏼  Welcome, @thatGreekGuy96! As far as I can tell, we haven't introduced any breaking change. At least, not deliberately.

Said that, it looks like the machine image doesn't have CML available in the executable path. Which AWS region are you on?

**Comment by DavidGOrtega** [comment] 2021-05-19 10:05
@0x2b3bfa0 we have removed the await inside CML

**Comment by thatGreekGuy96** [comment] 2021-05-19 10:06
> 👋🏼 Welcome, @thatGreekGuy96! As far as I can tell, we haven't introduced any breaking change. At least, not deliberately.
> 
> Said that, it looks like the machine image doesn't have CML available in the executable path. Which AWS region are you on?

We're in `eu-west-2`. As I said in my initial post, everything was working fine until this morning.

**Comment by thatGreekGuy96** [comment] 2021-05-19 10:09
Update: I've retried, while also adding `--cloud-startup-script=$(echo 'sudo apt update && sudo apt-get install --yes ec2-instance-connect' | base64 --wrap 0)` to the `cml-runner` command. I can now connect using EC2 instance connect but the github action still fails. 

If you have indeed made updates, is there a way for me to explicitly specify which version of the cml-runner command I'm using? So that I can roll back to the one that was working for us.

**Comment by 0x2b3bfa0** [comment] 2021-05-19 10:14
> @0x2b3bfa0 we have removed the await inside CML depending now exclusively on TF 🤔

Nothing to do with this; please refer to [the error message above](https://github.com/iterative/cml/issues/536#issuecomment-843943565).

**Comment by 0x2b3bfa0** [comment] 2021-05-19 10:15
> We're in `eu-west-2`. As I said in my initial post, everything was working fine until this morning.

The `eu-west-2` region should use our custom machine images with everything installed. 🤔

**Comment by thatGreekGuy96** [comment] 2021-05-19 10:21
@0x2b3bfa0 here is the AMI used by the instances in case it helps 

<img width="291" alt="image" src="https://user-images.githubusercontent.com/42438403/118797278-54a98b00-b894-11eb-8564-833031c8bc31.png">

**Comment by DavidGOrtega** [comment] 2021-05-19 11:13
@thatGreekGuy96 we have identified the potential issue. hopefully it will be fixed within the next hour

**Comment by DavidGOrtega** [comment] 2021-05-19 11:39
@thatGreekGuy96 I can confirm that the issue should be now fixed. Could you please confirm it?
Thank you for your support 🙏

**Comment by 0x2b3bfa0** [comment] 2021-05-19 15:45
@thatGreekGuy96, the cloud runner initialization script was installing the [`@dvcorg/cml`](https://www.npmjs.com/package/@dvcorg/cml) package from an unprivileged user account which didn't have enough permissions to install some [native addons](https://nodejs.org/api/addons.html) required by the [`mmmagic`](https://www.npmjs.com/package/mmmagic) package — which [relies on `libmagic`](https://github.com/mscdex/mmmagic/blob/master/deps/libmagic/libmagic.gyp) under the hood.

We fixed it with the https://github.com/iterative/terraform-provider-iterative/commit/5f62a02d428eb9f6961e1f0721ec76364d7fe347 commit.

```console
gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/12.20.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/@dvcorg/cml/node_modules/mmmagic/.node-gyp"
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/@dvcorg/cml/node_modules/mmmagic/.node-gyp'
gyp ERR! System Linux 5.4.0-1035-aws
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/@dvcorg/cml/node_modules/mmmagic
gyp ERR! node -v v12.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mmmagic@0.5.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mmmagic@0.5.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2021-05-19T08_25_12_292Z-debug.log
```

**Closed by 0x2b3bfa0** 2021-05-19 15:45 UTC
Labels: bug, p0-critical
